# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.7
repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: ["sarlo", "--line-length=120", "--target-version=py37"]
- repo: https://github.com/pycqa/flake8
  rev: master
  hooks:
    - id: flake8
      args: ["--select=C,E,F,W,B,B950", "--max-line-length=88", "--ignore=E203,E501,W503,F401"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
